#!/usr/bin/env php
<?php
/*
 * NanoPHP console bootstrap
 *
 */

// Require composer autoloader
require("vendor/autoload.php");

// Get main config file for the basic application
$config = require('config/console.php');

// Create an application instance and start!
(new nanophp\Libraries\Application($config))->run();
